---
version: "2.1"
services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: grav
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /portainer/Files/AppData/Config/grav:/config
    ports:
      - 8123:80
    restart: unless-stopped