---
- name: Configure Server and Deploy Docker
  hosts: servers
  become: true
  tasks:
    - name: Update and upgrade the server
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Docker.io and Docker Compose
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose

    - name: Log in to ghcr.io for Docker
      command: "" #add command

    - name: Create /inference directory
      file:
        path: /inference
        state: directory
        mode: '0755'

    - name: Create Docker Compose file
      copy:
        content: |
          version: '3'
          services:
            inference:
              image: ghcr.io/aimg1/inference:sha-5df8cd7
              runtime: nvidia
              environment:
                - MODEL=lmsys/vicuna-7b-v1.5
                - NATS_URLS=nats://0.0.0.0:4222
              command: bash run.sh
        dest: /inference/docker-compose.yml