---
- name: Reboot API Servers
  hosts: api_servers
  become: yes  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Reboot host
      command: "sudo reboot"

    - name: Wait for 30 seconds before proceeding to the next server
      wait_for:
        timeout: 30
      delegate_to: localhost
      when: inventory_hostname != ansible_play_hosts_all[-1]