version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: "aimg-redis"
    ports:
      - "16681:6379"
    volumes:
      - "/portainer/Files/AppData/Config/redis:/data"
    command: ["redis-server", "--appendonly", "yes"]
